export type DirectoryTool = {
  id: number;
  name: string;
  description: string;
  role: string;
  tag: string;
  image: string;
  url: string;
};

export const roles = [
  "App Builder",
  "Automation",
  "Community",
  "Content Creator",
  "Data & Analytics",
  "Design",
  "E-Commerce",
  "Education",
  "Finance",
  "Marketing",
  "Operations",
  "Product Management",
  "Sales",
  "Website Builder",
];

export const tags = [
  "AI-Powered",
  "API Connector",
  "Chatbot Builder",
  "CRM",
  "Dashboard",
  "Database",
  "Drag & Drop",
  "Email Marketing",
  "Form Builder",
  "Free Tier",
  "Integration",
  "Internal Tools",
  "Landing Pages",
  "Low-Code",
  "Membership",
  "Mobile App",
  "Open Source",
  "Payment",
  "Scheduling",
  "SEO",
  "Social Media",
  "Survey",
  "Template",
  "Video",
  "Voice AI",
  "Webhooks",
  "Workflow",
  "Zapier Alternative",
];

export const directoryTools: DirectoryTool[] = [
  {
    id: 1,
    name: "Bubble",
    description: "Build production-ready web apps without code. Full-stack visual programming.",
    role: "App Builder",
    tag: "Drag & Drop",
    image: "https://ui-avatars.com/api/?name=Bubble&background=6366f1&color=fff&size=128",
    url: "#",
  },
  {
    id: 2,
    name: "Webflow",
    description: "Design and build professional websites visually with full CSS control.",
    role: "Website Builder",
    tag: "Drag & Drop",
    image: "https://ui-avatars.com/api/?name=Webflow&background=4338ca&color=fff&size=128",
    url: "#",
  },
  {
    id: 3,
    name: "Airtable",
    description: "Spreadsheet-database hybrid for organizing anything. Build apps on top of your data.",
    role: "Data & Analytics",
    tag: "Database",
    image: "https://ui-avatars.com/api/?name=Airtable&background=14b8a6&color=fff&size=128",
    url: "#",
  },
  {
    id: 4,
    name: "Zapier",
    description: "Connect your apps and automate workflows with easy-to-build triggers and actions.",
    role: "Automation",
    tag: "Workflow",
    image: "https://ui-avatars.com/api/?name=Zapier&background=f97316&color=fff&size=128",
    url: "#",
  },
  {
    id: 5,
    name: "Notion",
    description: "All-in-one workspace for notes, docs, project management, and wikis.",
    role: "Operations",
    tag: "Template",
    image: "https://ui-avatars.com/api/?name=Notion&background=1e293b&color=fff&size=128",
    url: "#",
  },
  {
    id: 6,
    name: "Canva",
    description: "Create stunning graphics, presentations, and social media content with drag & drop.",
    role: "Design",
    tag: "Template",
    image: "https://ui-avatars.com/api/?name=Canva&background=7c3aed&color=fff&size=128",
    url: "#",
  },
  {
    id: 7,
    name: "Shopify",
    description: "Build your online store with no code. Full e-commerce platform for creators.",
    role: "E-Commerce",
    tag: "Payment",
    image: "https://ui-avatars.com/api/?name=Shopify&background=16a34a&color=fff&size=128",
    url: "#",
  },
  {
    id: 8,
    name: "Mailchimp",
    description: "Email marketing platform with automation, landing pages, and audience management.",
    role: "Marketing",
    tag: "Email Marketing",
    image: "https://ui-avatars.com/api/?name=Mailchimp&background=eab308&color=fff&size=128",
    url: "#",
  },
  {
    id: 9,
    name: "Typeform",
    description: "Beautiful, conversational forms and surveys that people enjoy filling out.",
    role: "Content Creator",
    tag: "Form Builder",
    image: "https://ui-avatars.com/api/?name=Typeform&background=0ea5e9&color=fff&size=128",
    url: "#",
  },
  {
    id: 10,
    name: "Retool",
    description: "Build internal tools fast with drag-and-drop components connected to your data.",
    role: "App Builder",
    tag: "Internal Tools",
    image: "https://ui-avatars.com/api/?name=Retool&background=dc2626&color=fff&size=128",
    url: "#",
  },
  {
    id: 11,
    name: "Make (Integromat)",
    description: "Visual automation platform to design, build, and automate anything.",
    role: "Automation",
    tag: "Zapier Alternative",
    image: "https://ui-avatars.com/api/?name=Make&background=8b5cf6&color=fff&size=128",
    url: "#",
  },
  {
    id: 12,
    name: "Framer",
    description: "Design and publish stunning sites with animations and CMS — no code needed.",
    role: "Website Builder",
    tag: "AI-Powered",
    image: "https://ui-avatars.com/api/?name=Framer&background=0d9488&color=fff&size=128",
    url: "#",
  },
  {
    id: 13,
    name: "Softr",
    description: "Turn your Airtable or Google Sheets data into client portals and internal tools.",
    role: "App Builder",
    tag: "Database",
    image: "https://ui-avatars.com/api/?name=Softr&background=2563eb&color=fff&size=128",
    url: "#",
  },
  {
    id: 14,
    name: "Glide",
    description: "Build mobile apps from spreadsheets. Perfect for internal tools and communities.",
    role: "App Builder",
    tag: "Mobile App",
    image: "https://ui-avatars.com/api/?name=Glide&background=059669&color=fff&size=128",
    url: "#",
  },
  {
    id: 15,
    name: "Thinkific",
    description: "Create, market, and sell online courses. Built for educators and creators.",
    role: "Education",
    tag: "Membership",
    image: "https://ui-avatars.com/api/?name=Thinkific&background=d946ef&color=fff&size=128",
    url: "#",
  },
  {
    id: 16,
    name: "Memberstack",
    description: "Add memberships, gated content, and payments to any website.",
    role: "Community",
    tag: "Membership",
    image: "https://ui-avatars.com/api/?name=Memberstack&background=6366f1&color=fff&size=128",
    url: "#",
  },
  {
    id: 17,
    name: "Carrd",
    description: "Simple, free, fully responsive one-page sites for pretty much anything.",
    role: "Website Builder",
    tag: "Landing Pages",
    image: "https://ui-avatars.com/api/?name=Carrd&background=f43f5e&color=fff&size=128",
    url: "#",
  },
  {
    id: 18,
    name: "Tally",
    description: "The simplest way to create free forms. No sign-up required, unlimited forms.",
    role: "Content Creator",
    tag: "Form Builder",
    image: "https://ui-avatars.com/api/?name=Tally&background=3b82f6&color=fff&size=128",
    url: "#",
  },
  {
    id: 19,
    name: "Stripe",
    description: "Payment infrastructure for the internet. Accept payments with no code via links.",
    role: "Finance",
    tag: "Payment",
    image: "https://ui-avatars.com/api/?name=Stripe&background=6366f1&color=fff&size=128",
    url: "#",
  },
  {
    id: 20,
    name: "Calendly",
    description: "Scheduling automation platform — eliminate the back and forth of meeting setup.",
    role: "Sales",
    tag: "Scheduling",
    image: "https://ui-avatars.com/api/?name=Calendly&background=2563eb&color=fff&size=128",
    url: "#",
  },
  {
    id: 21,
    name: "Adalo",
    description: "Build custom mobile and web apps without coding using a drag-and-drop builder.",
    role: "App Builder",
    tag: "Mobile App",
    image: "https://ui-avatars.com/api/?name=Adalo&background=ec4899&color=fff&size=128",
    url: "#",
  },
  {
    id: 22,
    name: "Teachable",
    description: "Create and sell online courses and coaching from your own branded platform.",
    role: "Education",
    tag: "Membership",
    image: "https://ui-avatars.com/api/?name=Teachable&background=0891b2&color=fff&size=128",
    url: "#",
  },
  {
    id: 23,
    name: "ConvertKit",
    description: "Email marketing built for creators. Grow your audience and monetize your work.",
    role: "Marketing",
    tag: "Email Marketing",
    image: "https://ui-avatars.com/api/?name=ConvertKit&background=fb7185&color=fff&size=128",
    url: "#",
  },
  {
    id: 24,
    name: "Supabase",
    description: "Open source Firebase alternative with Postgres database, auth, and real-time.",
    role: "Data & Analytics",
    tag: "Open Source",
    image: "https://ui-avatars.com/api/?name=Supabase&background=22c55e&color=fff&size=128",
    url: "#",
  },
  {
    id: 25,
    name: "Voiceflow",
    description: "Design, prototype, and build voice and chat AI assistants — no code required.",
    role: "Product Management",
    tag: "Voice AI",
    image: "https://ui-avatars.com/api/?name=Voiceflow&background=1e40af&color=fff&size=128",
    url: "#",
  },
  {
    id: 26,
    name: "Gumroad",
    description: "Sell digital products, memberships, and more directly to your audience.",
    role: "E-Commerce",
    tag: "Payment",
    image: "https://ui-avatars.com/api/?name=Gumroad&background=f472b6&color=fff&size=128",
    url: "#",
  },
  {
    id: 27,
    name: "Whalesync",
    description: "Two-way sync between Airtable, Webflow, Notion, and more. Keep data in sync.",
    role: "Automation",
    tag: "Integration",
    image: "https://ui-avatars.com/api/?name=Whalesync&background=6366f1&color=fff&size=128",
    url: "#",
  },
  {
    id: 28,
    name: "Coda",
    description: "All-in-one doc that combines documents, spreadsheets, and app-building blocks.",
    role: "Operations",
    tag: "Template",
    image: "https://ui-avatars.com/api/?name=Coda&background=f59e0b&color=fff&size=128",
    url: "#",
  },
  {
    id: 29,
    name: "Descript",
    description: "Edit video and podcasts as easily as a doc. AI-powered media editing.",
    role: "Content Creator",
    tag: "Video",
    image: "https://ui-avatars.com/api/?name=Descript&background=10b981&color=fff&size=128",
    url: "#",
  },
  {
    id: 30,
    name: "n8n",
    description: "Fair-code workflow automation tool. Self-hostable Zapier alternative.",
    role: "Automation",
    tag: "Open Source",
    image: "https://ui-avatars.com/api/?name=n8n&background=ea580c&color=fff&size=128",
    url: "#",
  },
  {
    id: 31,
    name: "Webstudio",
    description: "Open source visual builder that generates standards-compliant CSS and HTML.",
    role: "Website Builder",
    tag: "Open Source",
    image: "https://ui-avatars.com/api/?name=Webstudio&background=7c3aed&color=fff&size=128",
    url: "#",
  },
  {
    id: 32,
    name: "Lemon Squeezy",
    description: "All-in-one platform for selling digital products, subscriptions, and SaaS.",
    role: "E-Commerce",
    tag: "Payment",
    image: "https://ui-avatars.com/api/?name=Lemon+Squeezy&background=facc15&color=000&size=128",
    url: "#",
  },
  {
    id: 33,
    name: "Pabbly Connect",
    description: "Automate workflows between apps. One-time payment, no monthly fees.",
    role: "Automation",
    tag: "Zapier Alternative",
    image: "https://ui-avatars.com/api/?name=Pabbly&background=3b82f6&color=fff&size=128",
    url: "#",
  },
  {
    id: 34,
    name: "Landbot",
    description: "Build chatbots for your website, WhatsApp, and Facebook — no code needed.",
    role: "Marketing",
    tag: "Chatbot Builder",
    image: "https://ui-avatars.com/api/?name=Landbot&background=0ea5e9&color=fff&size=128",
    url: "#",
  },
  {
    id: 35,
    name: "Stacker",
    description: "Build custom portals and CRMs on top of Airtable, Google Sheets, and Salesforce.",
    role: "Sales",
    tag: "CRM",
    image: "https://ui-avatars.com/api/?name=Stacker&background=4f46e5&color=fff&size=128",
    url: "#",
  },
  {
    id: 36,
    name: "AppSheet",
    description: "Google's no-code app builder. Create apps from spreadsheets automatically.",
    role: "App Builder",
    tag: "AI-Powered",
    image: "https://ui-avatars.com/api/?name=AppSheet&background=16a34a&color=fff&size=128",
    url: "#",
  },
];
